### PR TITLE
Added error checking, Domestic Hot Water temperature and Poll Interval

### PR DESCRIPTION
**Pull request by gizmocuz**
Implemented:
- Error Checking
- Domestic Hot Water temperature
- Poll Interval

Please use the "Merge" option here

### CODE REVIEW

**Review by tuk90 — COMMENTED** [review]
Why did you comment out the lines 234 till 243, this means that it will always update the devices right?

**Comment by gizmocuz** [comment]
That's correct, It will update every minute (or at your poll interval). This should not be a problem?

**Comment by tuk90** [comment]
I always like to do stuff when they are neccecary and if the values did not change then why should I update them?

**Comment by gizmocuz** [comment]
So you know that they are updated.... For instance, when you have a zigbee/RF temperature sensor, it also updates at certain intervals.
And there is no issue with it. Domoticz makes a shortlog at a 5 minute interval... does not matter is there are 100.000 updates in between

**Pull request merged**
